.TH "Chart" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Chart
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBformatData\fP ($chart, $data)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
