.TH "AppServiceProvider" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppServiceProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits ServiceProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBboot\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boot ()"
Bootstrap any application services\&. 
.SS "register ()"
Register any application services\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
