.TH "VerifyEmailController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VerifyEmailController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__invoke\fP (EmailVerificationRequest $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "__invoke (EmailVerificationRequest $request)"
Mark the authenticated user's email address as verified\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
