.TH "SupplierOORImport" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SupplierOORImport
.SH SYNOPSIS
.br
.PP
.PP
Inherits WithMultipleSheets\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsheets\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
