.TH "Comment" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Comment
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuser\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaddComment\fP ($activity_id, $line_id, $po_id, $sku_id, $line, $identifier, $comment)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
