.TH "LineLateListener" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LineLateListener
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBhandle\fP (\fBLineLate\fP $event)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"
Create the event listener\&. 
.SH "Member Function Documentation"
.PP 
.SS "handle (\fBLineLate\fP $event)"
Handle the event\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
