.TH "LineActivity" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LineActivity
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtouchpoint\fP ()"
.br
.ti -1c
.RI "\fBtouchpointmodel\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
