.TH "RedirectIfAuthenticated" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RedirectIfAuthenticated
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhandle\fP (Request $request, Closure $next, string \&.\&.\&. $guards)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "handle (Request $request, Closure $next, string \&.\&.\&. $guards)"
Handle an incoming request\&.

.PP
\fBParameters\fP
.RS 4
\fI\fP .RE
.PP
Closure(\\Illuminate\\Http\\Request): (\\Symfony\\Component\\HttpFoundation\\Response) $next 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
