.TH "OorExport" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OorExport
.SH SYNOPSIS
.br
.PP
.PP
Inherits FromView\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($id)"
.br
.ti -1c
.RI "\fBview\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "view ()"

.PP
\fBReturns\fP
.RS 4
OOR $oor 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
