.TH "User_Supplier" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User_Supplier
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsupplier\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaddSuppliersToUser\fP ($user_id, $suppliers)"
.br
.ti -1c
.RI "static \fBgetAssignedSuppliers\fP ($user_id)"
.br
.ti -1c
.RI "static \fBgetAssignedUsers\fP ($team)"
.br
.ti -1c
.RI "static \fBgetSuppliers\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'user_suppliers'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
