.TH "EmailVerificationPromptController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmailVerificationPromptController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__invoke\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "__invoke (Request $request)"
Display the email verification prompt\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
