.TH "Controller" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseController\&.
.PP
Inherited by \fBAuthenticatedSessionController\fP, \fBConfirmablePasswordController\fP, \fBEmailVerificationNotificationController\fP, \fBEmailVerificationPromptController\fP, \fBNewPasswordController\fP, \fBPasswordController\fP, \fBPasswordResetLinkController\fP, \fBRegisteredUserController\fP, \fBVerifyEmailController\fP, \fBColumnController\fP, \fBContactController\fP, \fBDashboardController\fP, \fBEmailController\fP, \fBEscalationController\fP, \fBFinishedPartsController\fP, \fBHomeController\fP, \fBImportController\fP, \fBIngestionController\fP, \fBLineController\fP, \fBMeetingController\fP, \fBOrderController\fP, \fBPlantController\fP, \fBProfileController\fP, \fBSKUController\fP, \fBSupplierController\fP, \fBTouchpointController\fP, and \fBUserController\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
