.TH "Handler" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Handler
.SH SYNOPSIS
.br
.PP
.PP
Inherits ExceptionHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregister\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$dontFlash\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "register ()"
Register the exception handling callbacks for the application\&. 
.SH "Field Documentation"
.PP 
.SS "$dontFlash\fR [protected]\fP"
\fBInitial value:\fP
.nf
= [
        'current_password',
        'password',
        'password_confirmation',
    ]
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
