.TH "Order" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Order
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlines\fP ()"
.br
.ti -1c
.RI "\fBplant\fP ()"
.br
.ti -1c
.RI "\fBsupplier\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBexists\fP ($po)"
.br
.ti -1c
.RI "static \fBgetOrder\fP ($id)"
.br
.ti -1c
.RI "static \fBgetOpenOrders\fP ()"
.br
.ti -1c
.RI "static \fBimport\fP ($supplier_id, $row)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$fillable\fP = ['PO', 'plant_id', 'supplier_id', 'document_date']"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
