.TH "RouteServiceProvider" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RouteServiceProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits ServiceProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBboot\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBHOME\fP = '/suppliers'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBmapWebRoutes\fP ()"
.br
.ti -1c
.RI "\fBmapApiRoutes\fP ()"
.br
.ti -1c
.RI "\fBcentralDomains\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boot ()"
Define your route model bindings, pattern filters, and other route configuration\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
