.TH "NewPasswordController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewPasswordController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreate\fP (Request $request)"
.br
.ti -1c
.RI "\fBstore\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "create (Request $request)"
Display the password reset view\&. 
.SS "store (Request $request)"
Handle an incoming new password request\&.

.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP
Illuminate\\Validation\\ValidationException 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
