.TH "EmailVerificationNotificationController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmailVerificationNotificationController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstore\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "store (Request $request)"
Send a new email verification notification\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
