.TH "ProfileUpdateRequest" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProfileUpdateRequest
.SH SYNOPSIS
.br
.PP
.PP
Inherits FormRequest\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrules\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "rules ()"
Get the validation rules that apply to the request\&.

.PP
\fBReturns\fP
.RS 4
array<string, \\Illuminate\\Contracts\\Validation\\Rule|array|string> 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
