.TH "Column_Map" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Column_Map
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetColumnByColumnID\fP ($column_id)"
.br
.ti -1c
.RI "static \fBgetMappedColumn\fP ($column)"
.br
.ti -1c
.RI "static \fBmapColumn\fP ($request)"
.br
.ti -1c
.RI "static \fBmapColumns\fP ($rows)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'column_maps'"
.br
.ti -1c
.RI "\fB$fillable\fP = ['column_id', 'column']"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
