.TH "ProfileController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProfileController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBedit\fP (Request $request)"
.br
.ti -1c
.RI "\fBupdate\fP (\fBProfileUpdateRequest\fP $request)"
.br
.ti -1c
.RI "\fBdestroy\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "destroy (Request $request)"
Delete the user's account\&. 
.SS "edit (Request $request)"
Display the user's profile form\&. 
.SS "update (\fBProfileUpdateRequest\fP $request)"
Update the user's profile information\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
