.TH "Touchpoint" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Touchpoint
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlineactivity\fP ()"
.br
.ti -1c
.RI "\fBcomment\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetTouchpoints\fP ()"
.br
.ti -1c
.RI "static \fBgetTouchpointsNegativelyAffectingScore\fP ($activities)"
.br
.ti -1c
.RI "static \fBcreateTouchpoint\fP ($request)"
.br
.ti -1c
.RI "static \fBgetByCode\fP ($code)"
.br
.ti -1c
.RI "static \fBgetTouchpoint\fP ($id)"
.br
.ti -1c
.RI "static \fBupdateTouchpoint\fP ($request)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
