.TH "TenancyServiceProvider" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TenancyServiceProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits ServiceProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBevents\fP ()"
.br
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBboot\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fB$controllerNamespace\fP = ''"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBbootEvents\fP ()"
.br
.ti -1c
.RI "\fBmapRoutes\fP ()"
.br
.ti -1c
.RI "\fBmakeTenancyMiddlewareHighestPriority\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
