.TH "Contact" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Contact
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBdeleteContact\fP ($contact_id)"
.br
.ti -1c
.RI "static \fBsaveContact\fP ($request)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
