.TH "FirstSheetImportBatch" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FirstSheetImportBatch
.SH SYNOPSIS
.br
.PP
.PP
Inherits ToModel, WithBatchInserts, and WithHeadingRow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmodel\fP (array $row)"
.br
.ti -1c
.RI "\fBbatchSize\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
