.TH "AuthenticatedSessionController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuthenticatedSessionController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP (\fBLoginRequest\fP $request)"
.br
.ti -1c
.RI "\fBdestroy\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "create ()"
Display the login view\&. 
.SS "destroy (Request $request)"
Destroy an authenticated session\&. 
.SS "store (\fBLoginRequest\fP $request)"
Handle an incoming authentication request\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
