.TH "Taskcomment" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Taskcomment
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuser\fP ()"
.br
.ti -1c
.RI "\fBtask\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaddComment\fP ($task_id, $comment)"
.br
.ti -1c
.RI "static \fBgetTaskComments\fP ($tasks)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
