.TH "Delta" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Delta
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcalculateChange\fP ($prev_value, $current_value, $column)"
.br
.ti -1c
.RI "static \fBdoesDeltaExist\fP ($ingestion_id, $identifier)"
.br
.ti -1c
.RI "static \fBrecordChange\fP ($prev_line, $current_line, $column)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
