.TH "ImportController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImportController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBimport\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
