.TH "EventServiceProvider" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventServiceProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits ServiceProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBboot\fP ()"
.br
.ti -1c
.RI "\fBshouldDiscoverEvents\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$listen\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boot ()"
Register any events for your application\&. 
.SS "shouldDiscoverEvents ()"
Determine if events and listeners should be automatically discovered\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
