.TH "Skudetail" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Skudetail
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaddImage\fP ($skudetail_id, $image)"
.br
.ti -1c
.RI "static \fBgetOrCreate\fP ($sku_id)"
.br
.ti -1c
.RI "static \fBsaveImage\fP ($sku_id, $image)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
