.TH "ConfirmablePasswordController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfirmablePasswordController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshow\fP ()"
.br
.ti -1c
.RI "\fBstore\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "show ()"
Show the confirm password view\&. 
.SS "store (Request $request)"
Confirm the user's password\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
