.TH "FirstSheetImportSupplier" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FirstSheetImportSupplier
.SH SYNOPSIS
.br
.PP
.PP
Inherits ToCollection, and WithHeadingRow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcollection\fP (Collection $rows)"
.br
.ti -1c
.RI "\fBchunkSize\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
