.TH "SupplierColumnMap" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SupplierColumnMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaddSupplierColumnMap\fP ($supplier_id, $json)"
.br
.ti -1c
.RI "static \fBdoesSupplierMapExist\fP ($supplier_id)"
.br
.ti -1c
.RI "static \fBcreateMap\fP ($request)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
