.TH "RandomOORExport" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomOORExport
.SH SYNOPSIS
.br
.PP
.PP
Inherits FromGenerator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgenerator\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "generator ()"

.PP
\fBReturns\fP
.RS 4
\\Illuminate\\Support\\Collection 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
