.TH "MeetingItem" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeetingItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuser\fP ()"
.br
.ti -1c
.RI "\fBmeetingitemtype\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaddMeetingItem\fP ($request)"
.br
.ti -1c
.RI "static \fBgetItemsByMeetingId\fP ($meeting_id)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
