.TH "Supplierscore" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Supplierscore
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtouchpoint\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaddScore\fP ($supplier_id, $touchpoint)"
.br
.ti -1c
.RI "static \fBgetScoreData\fP ($supplier_id)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
