.TH "FinishedPart" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FinishedPart
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBparts\fP ()"
.br
.ti -1c
.RI "\fBsku\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBbuildSupplyChain\fP ($parts)"
.br
.ti -1c
.RI "static \fBgetCommitsForCalendar\fP ($parts)"
.br
.ti -1c
.RI "static \fBwritePartDescription\fP ($finishedpart)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
