.TH "PasswordResetLinkController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PasswordResetLinkController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "create ()"
Display the password reset link request view\&. 
.SS "store (Request $request)"
Handle an incoming password reset link request\&.

.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP
Illuminate\\Validation\\ValidationException 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
