.TH "BroadcastServiceProvider" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BroadcastServiceProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits ServiceProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBboot\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boot ()"
Bootstrap any application services\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
