.TH "LoginRequest" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoginRequest
.SH SYNOPSIS
.br
.PP
.PP
Inherits FormRequest\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBauthorize\fP ()"
.br
.ti -1c
.RI "\fBrules\fP ()"
.br
.ti -1c
.RI "\fBauthenticate\fP ()"
.br
.ti -1c
.RI "\fBensureIsNotRateLimited\fP ()"
.br
.ti -1c
.RI "\fBthrottleKey\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "authenticate ()"
Attempt to authenticate the request's credentials\&.

.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP
Illuminate\\Validation\\ValidationException 
.SS "authorize ()"
Determine if the user is authorized to make this request\&. 
.SS "ensureIsNotRateLimited ()"
Ensure the login request is not rate limited\&.

.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP
Illuminate\\Validation\\ValidationException 
.SS "rules ()"
Get the validation rules that apply to the request\&.

.PP
\fBReturns\fP
.RS 4
array<string, \\Illuminate\\Contracts\\Validation\\Rule|array|string> 
.RE
.PP

.SS "throttleKey ()"
Get the rate limiting throttle key for the request\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
