.TH "Task" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Task
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetTasksByIdentifier\fP ($identifier)"
.br
.ti -1c
.RI "static \fBupdateTaskStatus\fP ($task_id, $taskcolumn_id)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
