.TH "HandleInertiaRequests" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HandleInertiaRequests
.SH SYNOPSIS
.br
.PP
.PP
Inherits Middleware\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBversion\fP (Request $request)"
.br
.ti -1c
.RI "\fBshare\fP (Request $request)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$rootView\fP = 'app'"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "share (Request $request)"
Define the props that are shared by default\&.

.PP
\fBReturns\fP
.RS 4
array<string, mixed> 
.RE
.PP

.SS "version (Request $request)"
Determine the current asset version\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
