.TH "LineNetPriceChanged" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LineNetPriceChanged
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBbroadcastOn\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"
Create a new event instance\&. 
.SH "Member Function Documentation"
.PP 
.SS "broadcastOn ()"
Get the channels the event should broadcast on\&.

.PP
\fBReturns\fP
.RS 4
array<int, \\Illuminate\\Broadcasting\\Channel> 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
