.TH "Kernel" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kernel
.SH SYNOPSIS
.br
.PP
.PP
Inherits ConsoleKernel\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBschedule\fP (Schedule $schedule)"
.br
.ti -1c
.RI "\fBcommands\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "commands ()\fR [protected]\fP"
Register the commands for the application\&. 
.SS "schedule (Schedule $schedule)\fR [protected]\fP"
Define the application's command schedule\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
