.TH "Escalation" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Escalation
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsupplier\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEscalateSupplier\fP ($supplier)"
.br
.ti -1c
.RI "static \fBEscalateSuppliers\fP ()"
.br
.ti -1c
.RI "static \fBgenerateAIPrompt\fP ($escalation, $touchpoints_negative, $line='')"
.br
.ti -1c
.RI "static \fBgenerateExecutiveSummary\fP ($escalation)"
.br
.ti -1c
.RI "static \fBgetEscalations\fP ()"
.br
.ti -1c
.RI "static \fBgetStats\fP ($escalations)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
