.TH "Meeting" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Meeting
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBagendaitems\fP ()"
.br
.ti -1c
.RI "\fBuser\fP ()"
.br
.ti -1c
.RI "\fBsupplier\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcreateMeeting\fP ($rows)"
.br
.ti -1c
.RI "static \fBgenerateAttendees\fP ($meeting)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
