.TH "TrustHosts" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrustHosts
.SH SYNOPSIS
.br
.PP
.PP
Inherits Middleware\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhosts\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "hosts ()"
Get the host patterns that should be trusted\&.

.PP
\fBReturns\fP
.RS 4
array<int, string|null> 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
