.TH "ImportOOR" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImportOOR
.SH SYNOPSIS
.br
.PP
.PP
Inherits Command\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhandle\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$signature\fP = 'import:oor'"
.br
.ti -1c
.RI "\fB$description\fP = 'Imports an OOR'"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "handle ()"
Execute the console command\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
