.TH "Authenticate" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Authenticate
.SH SYNOPSIS
.br
.PP
.PP
Inherits Middleware\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBredirectTo\fP (Request $request)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "redirectTo (Request $request)\fR [protected]\fP"
Get the path the user should be redirected to when they are not authenticated\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
