.TH "ColumnController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColumnController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmapcolumn\fP (Request $request)"
.br
.ti -1c
.RI "\fBmapcolumns\fP ()"
.br
.ti -1c
.RI "\fBmapcolumnssupplier\fP (Request $request)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
