.TH "Plant" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Plant
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBorders\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetMapMarkers\fP ($plants)"
.br
.ti -1c
.RI "static \fBgetPlants\fP ()"
.br
.ti -1c
.RI "static \fBsavePlant\fP ($request)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
