.TH "Ingestion" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ingestion
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlines\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBadd\fP ($filename)"
.br
.ti -1c
.RI "static \fBgetColumnNames\fP ($row)"
.br
.ti -1c
.RI "static \fBgetIngestions\fP ()"
.br
.ti -1c
.RI "static \fBgetLastTwoIngestions\fP ()"
.br
.ti -1c
.RI "static \fBupdateSupplierScores\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
