.TH "Column" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Column
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcolumn_map\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetColumns\fP ()"
.br
.ti -1c
.RI "static \fBmakeSupplierColumnMap\fP ($columns, $supplier_columns)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
