.TH "TouchpointController" 3 "Mouker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TouchpointController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP (Request $request)"
.br
.ti -1c
.RI "\fBshow\fP (string $id)"
.br
.ti -1c
.RI "\fBedit\fP (string $id)"
.br
.ti -1c
.RI "\fBupdate\fP (Request $request, string $id)"
.br
.ti -1c
.RI "\fBdestroy\fP (string $id)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "create ()"
Show the form for creating a new resource\&. 
.SS "destroy (string $id)"
Remove the specified resource from storage\&. 
.SS "edit (string $id)"
Show the form for editing the specified resource\&. 
.SS "index ()"
Display a listing of the resource\&. 
.SS "show (string $id)"
Display the specified resource\&. 
.SS "store (Request $request)"
Store a newly created resource in storage\&. 
.SS "update (Request $request, string $id)"
Update the specified resource in storage\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mouker from the source code\&.
